# Advance Data Transformation
Author: Kim Hazed Delfino

## Imports

In [1108]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import os, json
import warnings
warnings.filterwarnings('ignore')

## Load the Data

In [1109]:
superhero_info = pd.read_csv("/Users/kim/Documents/GitHub/repo/Advanced_Data_Transformation/superhero_info - superhero_info.csv")
superhero_powers  = pd.read_csv("/Users/kim/Documents/GitHub/repo/Advanced_Data_Transformation/superhero_powers - superhero_powers.csv")

## Exploratory Data Analysis

In [1110]:
superhero_info.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 463 entries, 0 to 462
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Hero|Publisher  463 non-null    object
 1   Gender          463 non-null    object
 2   Race            463 non-null    object
 3   Alignment       463 non-null    object
 4   Hair color      463 non-null    object
 5   Eye color       463 non-null    object
 6   Skin color      463 non-null    object
 7   Measurements    463 non-null    object
dtypes: object(8)
memory usage: 29.1+ KB

In [1111]:
superhero_powers.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 667 entries, 0 to 666
Data columns (total 2 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   hero_names  667 non-null    object
 1   Powers      667 non-null    object
dtypes: object(2)
memory usage: 10.5+ KB

In [1112]:
superhero_info.head()

,Hero|Publisher,Gender,Race,Alignment,Hair color,Eye color,Skin color,Measurements
0,A-Bomb|Marvel Comics,Male,Human,good,No Hair,yellow,Unknown,"{'Height': '203.0 cm', 'Weight': '441.0 kg'}"
1,Abe Sapien|Dark Horse Comics,Male,Icthyo Sapien,good,No Hair,blue,blue,"{'Height': '191.0 cm', 'Weight': '65.0 kg'}"
2,Abin Sur|DC Comics,Male,Ungaran,good,No Hair,blue,red,"{'Height': '185.0 cm', 'Weight': '90.0 kg'}"
3,Abomination|Marvel Comics,Male,Human / Radiation,bad,No Hair,green,Unknown,"{'Height': '203.0 cm', 'Weight': '441.0 kg'}"
4,Absorbing Man|Marvel Comics,Male,Human,bad,No Hair,blue,Unknown,"{'Height': '193.0 cm', 'Weight': '122.0 kg'}"

In [1113]:
superhero_powers.head()

    hero_names                                             Powers
0      3-D Man         Agility,Super Strength,Stamina,Super Speed
1       A-Bomb  Accelerated Healing,Durability,Longevity,Super...
2   Abe Sapien  Agility,Accelerated Healing,Cold Resistance,Du...
3     Abin Sur                                 Lantern Power Ring
4  Abomination  Accelerated Healing,Intelligence,Super Strengt...

## Data Transformation - Superhero_info

In [1114]:
# Separate hero name and publisher
superhero_info[["Hero_names", "Publisher"]] = superhero_info['Hero|Publisher'].str.split('|',expand=True)

In [1115]:
# Double check
superhero_info.head()

,Hero|Publisher,Gender,Race,Alignment,Hair color,Eye color,Skin color,Measurements,Hero_names,Publisher
0,A-Bomb|Marvel Comics,Male,Human,good,No Hair,yellow,Unknown,"{'Height': '203.0 cm', 'Weight': '441.0 kg'}",A-Bomb,Marvel Comics
1,Abe Sapien|Dark Horse Comics,Male,Icthyo Sapien,good,No Hair,blue,blue,"{'Height': '191.0 cm', 'Weight': '65.0 kg'}",Abe Sapien,Dark Horse Comics
2,Abin Sur|DC Comics,Male,Ungaran,good,No Hair,blue,red,"{'Height': '185.0 cm', 'Weight': '90.0 kg'}",Abin Sur,DC Comics
3,Abomination|Marvel Comics,Male,Human / Radiation,bad,No Hair,green,Unknown,"{'Height': '203.0 cm', 'Weight': '441.0 kg'}",Abomination,Marvel Comics
4,Absorbing Man|Marvel Comics,Male,Human,bad,No Hair,blue,Unknown,"{'Height': '193.0 cm', 'Weight': '122.0 kg'}",Absorbing Man,Marvel Comics

In [1116]:
# Drop Hero|Publisher
superhero_info.drop(columns='Hero|Publisher',inplace=True)

In [1117]:
# Double check
superhero_info.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 463 entries, 0 to 462
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Gender        463 non-null    object
 1   Race          463 non-null    object
 2   Alignment     463 non-null    object
 3   Hair color    463 non-null    object
 4   Eye color     463 non-null    object
 5   Skin color    463 non-null    object
 6   Measurements  463 non-null    object
 7   Hero_names    463 non-null    object
 8   Publisher     463 non-null    object
dtypes: object(9)
memory usage: 32.7+ KB

In [1118]:
# Replace single quote to double quote 
superhero_info['Measurements']=superhero_info['Measurements'].str.replace("'",'"')

In [1119]:
# Convert measurement from str to dict
superhero_info['Measurements']=superhero_info['Measurements'].apply(json.loads)

In [1120]:
# Double check
test=superhero_info.loc[0,'Measurements']
print(type(test))
test

<class 'dict'>

{'Height': '203.0 cm', 'Weight': '441.0 kg'}

In [1121]:
# separate heigh and weight from measurement
h_w = superhero_info['Measurements'].apply(pd.Series)
h_w

       Height    Weight
0    203.0 cm  441.0 kg
1    191.0 cm   65.0 kg
2    185.0 cm   90.0 kg
3    203.0 cm  441.0 kg
4    193.0 cm  122.0 kg
..        ...       ...
458  183.0 cm   83.0 kg
459  165.0 cm   52.0 kg
460   66.0 cm   17.0 kg
461  170.0 cm   57.0 kg
462  185.0 cm   81.0 kg

[463 rows x 2 columns]

In [1122]:
# Combine height and weight back to our dataset and drop measurements
superhero_info=pd.concat((superhero_info,h_w),axis=1).drop(columns='Measurements')
superhero_info.head()

,Gender,Race,Alignment,Hair color,Eye color,Skin color,Hero_names,Publisher,Height,Weight
0,Male,Human,good,No Hair,yellow,Unknown,A-Bomb,Marvel Comics,203.0 cm,441.0 kg
1,Male,Icthyo Sapien,good,No Hair,blue,blue,Abe Sapien,Dark Horse Comics,191.0 cm,65.0 kg
2,Male,Ungaran,good,No Hair,blue,red,Abin Sur,DC Comics,185.0 cm,90.0 kg
3,Male,Human / Radiation,bad,No Hair,green,Unknown,Abomination,Marvel Comics,203.0 cm,441.0 kg
4,Male,Human,bad,No Hair,blue,Unknown,Absorbing Man,Marvel Comics,193.0 cm,122.0 kg

In [1123]:
# Convert Height and weight into float 
superhero_info['Height(cm)'] = superhero_info['Height'].str.replace(" cm","").astype(float)
superhero_info['Weight(kg)'] = superhero_info['Weight'].str.replace(" kg","").astype(float)
# Drop the Height and Weight column
superhero_info.drop(columns=['Height','Weight'],inplace=True)
superhero_info.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 463 entries, 0 to 462
Data columns (total 10 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Gender      463 non-null    object
 1   Race        463 non-null    object
 2   Alignment   463 non-null    object
 3   Hair color  463 non-null    object
 4   Eye color   463 non-null    object
 5   Skin color  463 non-null    object
 6   Hero_names  463 non-null    object
 7   Publisher   463 non-null    object
 8   Height(cm)  463 non-null    float64
 9   Weight(kg)  463 non-null    float64
dtypes: float64(2), object(8)
memory usage: 36.3+ KB

In [1124]:
# Double check
superhero_info.head()

,Gender,Race,Alignment,Hair color,Eye color,Skin color,Hero_names,Publisher,Height(cm),Weight(kg)
0,Male,Human,good,No Hair,yellow,Unknown,A-Bomb,Marvel Comics,203.0,441.0
1,Male,Icthyo Sapien,good,No Hair,blue,blue,Abe Sapien,Dark Horse Comics,191.0,65.0
2,Male,Ungaran,good,No Hair,blue,red,Abin Sur,DC Comics,185.0,90.0
3,Male,Human / Radiation,bad,No Hair,green,Unknown,Abomination,Marvel Comics,203.0,441.0
4,Male,Human,bad,No Hair,blue,Unknown,Absorbing Man,Marvel Comics,193.0,122.0

## Data Transformation - Superhero Powers

In [1125]:
superhero_powers.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 667 entries, 0 to 666
Data columns (total 2 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   hero_names  667 non-null    object
 1   Powers      667 non-null    object
dtypes: object(2)
memory usage: 10.5+ KB

In [1126]:
# use only hero names that also in our info dataset
superhero_powers_filter = superhero_powers['hero_names'].isin(superhero_info['Hero_names'])
superhero_powers_df = superhero_powers[superhero_powers_filter].reset_index(drop=True)

In [1127]:
# Double check
superhero_powers_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 455 entries, 0 to 454
Data columns (total 2 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   hero_names  455 non-null    object
 1   Powers      455 non-null    object
dtypes: object(2)
memory usage: 7.2+ KB

In [1128]:
test_1 = superhero_powers_df.loc[1,"Powers"]
print(type(test_1))
test_1

<class 'str'>

'Agility,Accelerated Healing,Cold Resistance,Durability,Underwater breathing,Marksmanship,Weapons Master,Longevity,Intelligence,Super Strength,Telepathy,Stamina,Immortality,Reflexes,Enhanced Sight,Sub-Mariner'

In [1129]:
# Split and Explode the powers to separate each unique name
superhero_powers_df["Powers_split"]= superhero_powers_df["Powers"].str.split(',')
superhero_powers_df["Powers_split"]

0      [Accelerated Healing, Durability, Longevity, S...
1      [Agility, Accelerated Healing, Cold Resistance...
2                                   [Lantern Power Ring]
3      [Accelerated Healing, Intelligence, Super Stre...
4      [Cold Resistance, Durability, Energy Absorptio...
                             ...
450              [Size Changing, Animal Oriented Powers]
451               [Flight, Energy Blasts, Size Changing]
452    [Agility, Stealth, Danger Sense, Marksmanship,...
453    [Cryokinesis, Telepathy, Magic, Fire Control, ...
454    [Super Speed, Intangibility, Time Travel, Time...
Name: Powers_split, Length: 455, dtype: object

In [1130]:
test=superhero_powers_df.loc[1,"Powers"]
print(type(test))
test

<class 'str'>

'Agility,Accelerated Healing,Cold Resistance,Durability,Underwater breathing,Marksmanship,Weapons Master,Longevity,Intelligence,Super Strength,Telepathy,Stamina,Immortality,Reflexes,Enhanced Sight,Sub-Mariner'

In [1131]:
# Explode to get each power
exploded = superhero_powers_df.explode('Powers_split')
exploded

,hero_names,Powers,Powers_split
0,A-Bomb,"Accelerated Healing,Durability,Longevity,Super...",Accelerated Healing
0,A-Bomb,"Accelerated Healing,Durability,Longevity,Super...",Durability
0,A-Bomb,"Accelerated Healing,Durability,Longevity,Super...",Longevity
0,A-Bomb,"Accelerated Healing,Durability,Longevity,Super...",Super Strength
0,A-Bomb,"Accelerated Healing,Durability,Longevity,Super...",Stamina
...,...,...,...
453,Zatanna,"Cryokinesis,Telepathy,Magic,Fire Control,Proba...",Weather Control
454,Zoom,"Super Speed,Intangibility,Time Travel,Time Man...",Super Speed
454,Zoom,"Super Speed,Intangibility,Time Travel,Time Man...",Intangibility
454,Zoom,"Super Speed,Intangibility,Time Travel,Time Man...",Time Travel
454,Zoom,"Super Speed,Intangibility,Time Travel,Time Man...",Time Manipulation

In [1132]:
# Get unique power
cols_to_make = exploded['Powers_split'].dropna().unique()
cols_to_make

array(['Accelerated Healing', 'Durability', 'Longevity', 'Super Strength',
       'Stamina', 'Camouflage', 'Self-Sustenance', 'Agility',
       'Cold Resistance', 'Underwater breathing', 'Marksmanship',
       'Weapons Master', 'Intelligence', 'Telepathy', 'Immortality',
       'Reflexes', 'Enhanced Sight', 'Sub-Mariner', 'Lantern Power Ring',
       'Super Speed', 'Invulnerability', 'Animation', 'Super Breath',
       'Energy Absorption', 'Elemental Transmogrification',
       'Fire Resistance', 'Natural Armor', 'Molecular Manipulation',
       'Heat Resistance', 'Matter Absorption', 'Stealth', 'Flight',
       'Power Suit', 'Energy Blasts', 'Energy Beams', 'Power Cosmic',
       'Heat Generation', 'Danger Sense', 'Teleportation', 'Phasing',
       'Force Fields', 'Hypnokinesis', 'Energy Manipulation',
       'Invisibility', 'Enhanced Senses', 'Jump', 'Substance Secretion',
       'Natural Weapons', 'Wallcrawling', 'Vision - Thermal',
       'Power Augmentation', 'Cryokinesis', 'Duplication',
       'Size Changing', 'Weapon-based Powers', 'Shapeshifting',
       'Fire Control', 'Enhanced Memory', 'Energy Constructs',
       'Power Absorption', 'Enhanced Hearing', 'Time Travel',
       'Enhanced Smell', 'Water Control', 'Vision - Telescopic',
       'Magnetism', 'Vision - Microscopic', 'Vision - Night',
       'Vision - Heat', 'Vision - X-Ray', 'Magic', 'Psionic Powers',
       'Gliding', 'Toxin and Disease Resistance', 'Animal Attributes',
       'Animal Oriented Powers', 'Regeneration',
       'Toxin and Disease Control', 'Empathy', 'Animal Control',
       'Elasticity', 'Web Creation', 'Symbiote Costume', 'Telekinesis',
       'Levitation', 'Biokinesis', 'Sonar', 'Enhanced Touch',
       'Seismic Power', 'Energy Armor', 'Radiation Immunity',
       'Density Control', 'Light Control', 'Illumination',
       'Molecular Combustion', 'Dimensional Travel', 'Audio Control',
       'Sonic Scream', 'Peak Human Condition', 'Vision - Infrared',
       'Dexterity', 'Energy Resistance', 'Vision - Cryo', 'Clairvoyance',
       'Probability Manipulation', 'Electrokinesis',
       'Darkforce Manipulation', 'Illusions', 'Death Touch',
       'Gravity Control', 'Precognition', 'Time Manipulation',
       'Omnilingualism', 'Astral Projection', 'Technopath/Cyberpath',
       'Mind Control', 'Mind Blast', 'Cloaking', 'Telepathy Resistance',
       'Mind Control Resistance', 'Radiation Control',
       'Radiation Absorption', 'Magic Resistance',
       'Dimensional Awareness', 'Intangibility', 'Element Control',
       'Wind Control', 'Echolocation', 'Radar Sense', 'Resurrection',
       'The Force', 'Possession', 'Astral Travel', 'Summoning', 'Banish',
       'Adaptation', 'Electrical Transport', 'Speed Force', 'Omnipotent',
       'Grim Reaping', 'Reality Warping', 'Portal Creation',
       'Vitakinesis', 'Projection', 'Insanity', 'Plant Control',
       'Photographic Reflexes', 'Anti-Gravity', 'Power Nullifier',
       'Hair Manipulation', 'Weather Control', 'Nova Force', 'Odin Force',
       'Phoenix Force', 'Power Sense', 'Qwardian Power Ring', 'Melting',
       'Changing Armor', 'Terrakinesis'], dtype=object)

In [1133]:
# Create new col for each power and One-hot-encode each value
for col in cols_to_make:
    superhero_powers_df[col] = superhero_powers_df['Powers'].str.contains(col,na=False)
superhero_powers_df.head()

,hero_names,Powers,Powers_split,Accelerated Healing,Durability,Longevity,Super Strength,Stamina,Camouflage,Self-Sustenance,...,Hair Manipulation,Weather Control,Nova Force,Odin Force,Phoenix Force,Power Sense,Qwardian Power Ring,Melting,Changing Armor,Terrakinesis
0,A-Bomb,"Accelerated Healing,Durability,Longevity,Super...","[Accelerated Healing, Durability, Longevity, S...",True,True,True,True,True,True,True,...,False,False,False,False,False,False,False,False,False,False
1,Abe Sapien,"Agility,Accelerated Healing,Cold Resistance,Du...","[Agility, Accelerated Healing, Cold Resistance...",True,True,True,True,True,False,False,...,False,False,False,False,False,False,False,False,False,False
2,Abin Sur,Lantern Power Ring,[Lantern Power Ring],False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,Abomination,"Accelerated Healing,Intelligence,Super Strengt...","[Accelerated Healing, Intelligence, Super Stre...",True,False,False,True,True,False,False,...,False,False,False,False,False,False,False,False,False,False
4,Absorbing Man,"Cold Resistance,Durability,Energy Absorption,S...","[Cold Resistance, Durability, Energy Absorptio...",False,True,False,True,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [1134]:
# Drop power / power_split columns
superhero_powers_df.drop(columns=['Powers','Powers_split'],inplace=True)
superhero_powers_df.head()

,hero_names,Accelerated Healing,Durability,Longevity,Super Strength,Stamina,Camouflage,Self-Sustenance,Agility,Cold Resistance,...,Hair Manipulation,Weather Control,Nova Force,Odin Force,Phoenix Force,Power Sense,Qwardian Power Ring,Melting,Changing Armor,Terrakinesis
0,A-Bomb,True,True,True,True,True,True,True,False,False,...,False,False,False,False,False,False,False,False,False,False
1,Abe Sapien,True,True,True,True,True,False,False,True,True,...,False,False,False,False,False,False,False,False,False,False
2,Abin Sur,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,Abomination,True,False,False,True,True,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,Absorbing Man,False,True,False,True,False,False,False,False,True,...,False,False,False,False,False,False,False,False,False,False

In [1139]:
info_filter = superhero_info['Hero_names'].isin(superhero_powers_df['hero_names'])
superhero_info_df = superhero_info[info_filter]
superhero_info_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 463 entries, 0 to 462
Data columns (total 10 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Gender      463 non-null    object
 1   Race        463 non-null    object
 2   Alignment   463 non-null    object
 3   Hair color  463 non-null    object
 4   Eye color   463 non-null    object
 5   Skin color  463 non-null    object
 6   Hero_names  463 non-null    object
 7   Publisher   463 non-null    object
 8   Height(cm)  463 non-null    float64
 9   Weight(kg)  463 non-null    float64
dtypes: float64(2), object(8)
memory usage: 39.8+ KB

In [1140]:
superhero_info_df['Hero_names'].value_counts()

Spider-Man        3
Black Canary      2
Nova              2
Captain Marvel    2
Toxin             2
                 ..
Feral             1
Falcon            1
Fabian Cortez     1
Exodus            1
Zoom              1
Name: Hero_names, Length: 455, dtype: int64

In [1141]:
superhero_info_df[superhero_info_df['Hero_names']=="Spider-Man"]

,Gender,Race,Alignment,Hair color,Eye color,Skin color,Hero_names,Publisher,Height(cm),Weight(kg)
384,Male,Human,good,Brown,hazel,Unknown,Spider-Man,Marvel Comics,178.0,74.0
385,Unknown,Human,good,Brown,red,Unknown,Spider-Man,Marvel Comics,178.0,77.0
386,Male,Human,good,Black,brown,Unknown,Spider-Man,Marvel Comics,157.0,56.0

- Looks like we have same hero with multiple registry and different attributes, this will cause issues during concatinating of two datasets index will be offset causing superhero powers to mismatch creating NaN values

In [1142]:
hero_name_mapper = {}
duplicated = {}
counter = 0
# Seach for multiple hero name registry with different attributes
for hero_name in superhero_info_df['Hero_names']:
    if hero_name in hero_name_mapper.keys():
        if hero_name in duplicated:
            duplicated[hero_name].append(counter)
        else:
            duplicated[hero_name] = [counter]
    else:
        hero_name_mapper[hero_name]=[counter]
    counter+=1

In [1143]:
duplicated

{'Atlas': [33],
 'Batman': [46],
 'Black Canary': [61],
 'Captain Marvel': [94],
 'Nova': [304],
 'Spider-Man': [385, 386],
 'Toxin': [423]}

In [1144]:
# Drop all the duplicated super hero names 
superhero_info_df.drop([33,46,61,94,304,385,386,423],axis=0,inplace=True)
superhero_info_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 455 entries, 0 to 462
Data columns (total 10 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Gender      455 non-null    object
 1   Race        455 non-null    object
 2   Alignment   455 non-null    object
 3   Hair color  455 non-null    object
 4   Eye color   455 non-null    object
 5   Skin color  455 non-null    object
 6   Hero_names  455 non-null    object
 7   Publisher   455 non-null    object
 8   Height(cm)  455 non-null    float64
 9   Weight(kg)  455 non-null    float64
dtypes: float64(2), object(8)
memory usage: 39.1+ KB

In [1145]:
superhero_powers_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 455 entries, 0 to 454
Columns: 160 entries, hero_names to Terrakinesis
dtypes: bool(159), object(1)
memory usage: 74.3+ KB

In [1146]:
superhero_powers_df.tail()

,hero_names,Accelerated Healing,Durability,Longevity,Super Strength,Stamina,Camouflage,Self-Sustenance,Agility,Cold Resistance,...,Hair Manipulation,Weather Control,Nova Force,Odin Force,Phoenix Force,Power Sense,Qwardian Power Ring,Melting,Changing Armor,Terrakinesis
450,Yellowjacket,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
451,Yellowjacket II,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
452,Yoda,False,False,True,False,True,False,False,True,False,...,False,False,False,False,False,False,False,False,False,False
453,Zatanna,False,False,False,False,False,False,False,False,False,...,False,True,False,False,False,False,False,False,False,True
454,Zoom,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

- now that both our df has the same values of index we just need to reset the index numbers and then we can merge them both

In [1147]:
# Reset index 
superhero_info_df.reset_index(drop=True,inplace=True)
superhero_powers_df.reset_index(drop=True,inplace=True)

In [1148]:
superhero_info_df.tail()

,Gender,Race,Alignment,Hair color,Eye color,Skin color,Hero_names,Publisher,Height(cm),Weight(kg)
450,Male,Human,good,Blond,blue,Unknown,Yellowjacket,Marvel Comics,183.0,83.0
451,Female,Human,good,Strawberry Blond,blue,Unknown,Yellowjacket II,Marvel Comics,165.0,52.0
452,Male,Yoda's species,good,White,brown,green,Yoda,George Lucas,66.0,17.0
453,Female,Human,good,Black,blue,Unknown,Zatanna,DC Comics,170.0,57.0
454,Male,Unknown,bad,Brown,red,Unknown,Zoom,DC Comics,185.0,81.0

In [1149]:
# Move hero name to first column
poped = superhero_info_df.pop('Hero_names')
superhero_info_df.insert(0,"Hero_names",poped)
superhero_info_df.head()

,Hero_names,Gender,Race,Alignment,Hair color,Eye color,Skin color,Publisher,Height(cm),Weight(kg)
0,A-Bomb,Male,Human,good,No Hair,yellow,Unknown,Marvel Comics,203.0,441.0
1,Abe Sapien,Male,Icthyo Sapien,good,No Hair,blue,blue,Dark Horse Comics,191.0,65.0
2,Abin Sur,Male,Ungaran,good,No Hair,blue,red,DC Comics,185.0,90.0
3,Abomination,Male,Human / Radiation,bad,No Hair,green,Unknown,Marvel Comics,203.0,441.0
4,Absorbing Man,Male,Human,bad,No Hair,blue,Unknown,Marvel Comics,193.0,122.0

In [1153]:
# Combine two df 
sh_combined_df = pd.concat([superhero_info_df,superhero_powers_df],axis=1,join='inner')
sh_combined_df.head()

,Hero_names,Gender,Race,Alignment,Hair color,Eye color,Skin color,Publisher,Height(cm),Weight(kg),...,Hair Manipulation,Weather Control,Nova Force,Odin Force,Phoenix Force,Power Sense,Qwardian Power Ring,Melting,Changing Armor,Terrakinesis
0,A-Bomb,Male,Human,good,No Hair,yellow,Unknown,Marvel Comics,203.0,441.0,...,False,False,False,False,False,False,False,False,False,False
1,Abe Sapien,Male,Icthyo Sapien,good,No Hair,blue,blue,Dark Horse Comics,191.0,65.0,...,False,False,False,False,False,False,False,False,False,False
2,Abin Sur,Male,Ungaran,good,No Hair,blue,red,DC Comics,185.0,90.0,...,False,False,False,False,False,False,False,False,False,False
3,Abomination,Male,Human / Radiation,bad,No Hair,green,Unknown,Marvel Comics,203.0,441.0,...,False,False,False,False,False,False,False,False,False,False
4,Absorbing Man,Male,Human,bad,No Hair,blue,Unknown,Marvel Comics,193.0,122.0,...,False,False,False,False,False,False,False,False,False,False

In [1151]:
sh_combined_df.tail()

,hero_names,Accelerated Healing,Durability,Longevity,Super Strength,Stamina,Camouflage,Self-Sustenance,Agility,Cold Resistance,...,Hero_names,Gender,Race,Alignment,Hair color,Eye color,Skin color,Publisher,Height(cm),Weight(kg)
450,Yellowjacket,False,False,False,False,False,False,False,False,False,...,Yellowjacket,Male,Human,good,Blond,blue,Unknown,Marvel Comics,183.0,83.0
451,Yellowjacket II,False,False,False,False,False,False,False,False,False,...,Yellowjacket II,Female,Human,good,Strawberry Blond,blue,Unknown,Marvel Comics,165.0,52.0
452,Yoda,False,False,True,False,True,False,False,True,False,...,Yoda,Male,Yoda's species,good,White,brown,green,George Lucas,66.0,17.0
453,Zatanna,False,False,False,False,False,False,False,False,False,...,Zatanna,Female,Human,good,Black,blue,Unknown,DC Comics,170.0,57.0
454,Zoom,False,False,False,False,False,False,False,False,False,...,Zoom,Male,Unknown,bad,Brown,red,Unknown,DC Comics,185.0,81.0

In [1154]:
# now we can drop the other hero_names from one of the df 
sh_combined_df.drop(columns='hero_names',inplace=True)
sh_combined_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 455 entries, 0 to 454
Columns: 169 entries, Hero_names to Terrakinesis
dtypes: bool(159), float64(2), object(8)
memory usage: 106.3+ KB

In [1156]:
sh_combined_df.head()

,Hero_names,Gender,Race,Alignment,Hair color,Eye color,Skin color,Publisher,Height(cm),Weight(kg),...,Hair Manipulation,Weather Control,Nova Force,Odin Force,Phoenix Force,Power Sense,Qwardian Power Ring,Melting,Changing Armor,Terrakinesis
0,A-Bomb,Male,Human,good,No Hair,yellow,Unknown,Marvel Comics,203.0,441.0,...,False,False,False,False,False,False,False,False,False,False
1,Abe Sapien,Male,Icthyo Sapien,good,No Hair,blue,blue,Dark Horse Comics,191.0,65.0,...,False,False,False,False,False,False,False,False,False,False
2,Abin Sur,Male,Ungaran,good,No Hair,blue,red,DC Comics,185.0,90.0,...,False,False,False,False,False,False,False,False,False,False
3,Abomination,Male,Human / Radiation,bad,No Hair,green,Unknown,Marvel Comics,203.0,441.0,...,False,False,False,False,False,False,False,False,False,False
4,Absorbing Man,Male,Human,bad,No Hair,blue,Unknown,Marvel Comics,193.0,122.0,...,False,False,False,False,False,False,False,False,False,False

## II. Use your combined DataFrame to answer the following questions.

- Compare the average weight of super powers who have Super Speed to those who do not.
- What is the average height of heroes for each publisher?

In [1157]:
# create filter for heroes with super speed 
speedy_filter = sh_combined_df['Super Speed'] == True

In [1158]:
# group the speedy and non speedy
speedsters = sh_combined_df[speedy_filter]
slowpokes = sh_combined_df[~speedy_filter]

In [1161]:
# get avg weight for speedy and slowpokes 
print(f"Avg weight for heroes with super speed is {round(speedsters['Weight(kg)'].mean())}kg")
print(f"Avg weight for slowpokes heros is {round(slowpokes['Weight(kg)'].mean())}kg")

Avg weight for heroes with super speed is 132kg
Avg weight for slowpokes heros is 101kg

In [1162]:
# Get avg height of heroes per publisher
sh_combined_df.groupby('Publisher')['Height(cm)'].mean()

Publisher
DC Comics            181.839552
Dark Horse Comics    176.909091
George Lucas         159.600000
Image Comics         211.000000
Marvel Comics        191.809556
Shueisha             171.500000
Star Trek            181.500000
Team Epic TV         180.750000
Unknown              178.000000
Name: Height(cm), dtype: float64